better4you/Better4You/UI/Better4You.UI.Mvc/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using MealConfig=Better4You.Meal.Config;
using Better4You.Meal.Service;
using Better4You.Meal.Service.Messages;
using Better4You.Meal.ViewModel;
using Better4You.Service;

using Tar.Service.Messages;
using TarView = Tar.ViewModel;



using Better4You.Core;


namespace Better4You.UI.Mvc.Controllers
{
    public class FoodController : ControllerBase
    {
        public ILookupService LookupService { get; set; }
        public IFoodService FoodService { get; set; }
        //
        // GET: /Food/

        public ActionResult Index()
        {
            ViewBag.FoodTypes = MealConfig.Lookups.GetItems<MealConfig.FoodTypes>();
            

            var request = new FoodGetAllRequest
                              {
                                  Filter = new FoodFilterView(),
                                  OrderByAsc = true,
                                  OrderByField = "Name",
                                  PageIndex = 1,
                                  PageSize = 20000
                              };
            TryUpdateModel(request.Filter);
            var result = FoodService.GetAllByFilter(request);
            return View(result.Foods);
        }

        [HttpPost]
        public JsonResult List()
        {
            var request = new FoodGetAllRequest
            {
                Filter = new FoodFilterView(),
                OrderByAsc = true,
                OrderByField = "Name",
                PageIndex = 1,
                PageSize = 20
            };
            TryUpdateModel(request.Filter);
            var result = FoodService.GetAllByFilter(request);
            return Json(result,JsonRequestBehavior.DenyGet);
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var mealTypeId = (int)MealConfig.MealTypes.Breakfast;

            if (!string.IsNullOrWhiteSpace(Request["MealTypeId"]))
                mealTypeId = Int32.Parse(Request["MealTypeId"]);


  
            var food = id.HasValue
                           ? FoodService.Get(new FoodGetRequest {Id = id.Value}).Food
                           : new FoodView { FoodType = MealConfig.Lookups.GetItem<MealConfig.FoodTypes>((long)MealConfig.FoodTypes.None) };


            var foodTypes = MealConfig.Lookups.GetItems<MealConfig.FoodTypes>().Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Text,
                Selected = d.Id == food.FoodType.Id
            }).ToList();


            ViewBag.FoodTypes = foodTypes;

            var ingredientTypes = MealConfig.Lookups.GetItems<MealConfig.IngredientTypes>().Where(d => d.Id > 0).ToList(); 

            var existIngredients = food.FoodIngredients.Select(d => d.IngredientType.Id).ToList();

            ingredientTypes.Where(d => existIngredients.Contains(d.Id)).ToList()
                .ForEach(d => food.FoodIngredients
                    .First(k => k.IngredientType.Id == d.Id).IngredientType = d);

            ingredientTypes.Where(d => !existIngredients.Contains(d.Id)).ToList()
                .ForEach(d => food.FoodIngredients.Add(new FoodIngredientView {IngredientType = d}));
            return View(food);
        }

        [HttpPost]
        public ActionResult Edit(FoodView request)
        {


            var foodTypeId = string.IsNullOrWhiteSpace(Request["FoodTypeId"])?0:Convert.ToInt32(Request["FoodTypeId"]);
            request.FoodType = MealConfig.Lookups.GetItem<MealConfig.FoodTypes>(foodTypeId);
            request.RecordStatus = MealConfig.Lookups.GetItem<RecordStatuses>((int)RecordStatuses.Active);
            
            for (int i = 0; i < request.FoodIngredients.Count; i++)
            {
                var ingredientTypeKey = Request[string.Format("FoodIngredients[{0}].IngredientType", i)];
                request.FoodIngredients[i].IngredientType = new TarView.GeneralItemView(Convert.ToInt32(ingredientTypeKey),
                    "", "");
                ModelState.Remove(string.Format("FoodIngredients[{0}].IngredientType", i));
            }


            var foodTypes = MealConfig.Lookups.GetItems<MealConfig.FoodTypes>().Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Text,
                Selected = d.Id == foodTypeId
            }).ToList();

            ViewBag.FoodTypes = foodTypes;

            if (foodTypeId > 0)
            {
                request.ModifiedBy = CurrentUser.Name;
                request.ModifiedByFullName = CurrentUser.FullName;
                if (!ModelState.IsValid) return View(request);
                if (request.Id == 0)
                {
                    var response = FoodService.Create(
                        new FoodCreateRequest
                            {
                                Food = request
                            });
                    if (response.Result == Result.Success)
                    {
                        InfoMessage = response.Message;
                        return RedirectToAction("Index");
                    }
                    ErrorMessage = response.Message;
                }
                else
                {
                    var response = FoodService.Update(new FoodUpdateRequest
                                                          {
                                                              Food = request
                                                          });
                    if (response.Result == Result.Success)
                    {
                        InfoMessage = response.Message;
                        return RedirectToAction("Index");
                    }
                    ErrorMessage = response.Message;
                }
            }
            else
            {
                ErrorMessage = "Food Type Not Selected";
            }

            var ingredientTypes = MealConfig.Lookups.GetItems<MealConfig.IngredientTypes>().Where(d => d.Id > 0).ToList();

            var existIngredients = request.FoodIngredients.Select(d => d.IngredientType.Id).ToList();
            ingredientTypes.Where(d => !existIngredients.Contains(d.Id)).ToList()
                .ForEach(d => request.FoodIngredients.Add(new FoodIngredientView {IngredientType = d}));


            ingredientTypes.Where(d => existIngredients.Contains(d.Id)).ToList()
                .ForEach(d => request.FoodIngredients
                                  .First(k => k.IngredientType.Id == d.Id).IngredientType = d);
            return View(request);
        }

        [HttpPost]
        public ActionResult Delete(FoodView request)
        {
            var response = FoodService.Delete(new FoodDeleteRequest { Food = request});
            if (response.Result == Result.Success)
            {
                InfoMessage = response.Message;
                return RedirectToAction("Index");
            }
            ErrorMessage = response.Message;
            return RedirectToAction("Edit", request);
        }

        public ActionResult Percentage()
        {
            var percentages = FoodService.GetFoodPercentages(new FoodPercentagesRequest { SchoolId = CurrentUser.CurrentSchoolId() });
            return View(percentages.PercentageList);
        }

        [HttpPost]
        public ActionResult Percentage(int foodPercentageCount)
        {
            var percentages = new List<FoodPercentageView>();
            for (int i = 0; i < foodPercentageCount; i++)
            {
                var mealType = Request[string.Format("FoodPercentages[{0}].MealType", i)];
                int fruitPr=200 ;
                int.TryParse(Request[string.Format("FoodPercentages[{0}].Fruit", i)], out fruitPr);
                int vegPr = 200;
                int.TryParse(Request[string.Format("FoodPercentages[{0}].Vegetable", i)], out vegPr);
                fruitPr = (fruitPr > 200 ? 200 : fruitPr);
                vegPr = (vegPr > 200 ? 200 : vegPr);
                percentages.Add(new FoodPercentageView
                {
                    SchoolId = CurrentUser.CurrentSchoolId() ,
                    Id = Convert.ToInt64(Request[string.Format("FoodPercentages[{0}].Id", i)]),
                    Fruit = fruitPr, Vegetable = vegPr, MealType = new TarView.GeneralItemView(Convert.ToInt32(mealType), "", "") });
            }
            var response = FoodService.SaveFoodPercentages(new FoodPercentagesSaveRequest{PercentageList = percentages});
            
            if (response.Result == Result.Success)
                InfoMessage = response.Message;                
            else ErrorMessage = response.Message;

            return RedirectToAction("Percentage");
        }

    }
}

better4you/Better4You/UI/Better4You.UI.Mvc/Views/Food/Edit.cshtml
@model FoodView
@{
    ViewBag.Title = string.Format("{0} Item", Model.Id == 0 ? "Create" : "Edit");
}

<!-- start: PAGE HEADER -->
<div class="row">
	<div class="col-sm-12">
		<!-- start: PAGE TITLE & BREADCRUMB -->
		<ol class="breadcrumb">
			<li>
			    <i class="clip-home-3"></i>
			    <a href="#">
			        Home
			    </a>
			</li>
		    <li>
			    <a href="@Url.Action("Index", "Food")">
			        Items
			    </a>
		    </li>
		    <li class="active">
		        @ViewBag.Title
		    </li>
		</ol>
	    <div class="row page-header">
	        <div class="col-sm-6">
	            <h1>
	                @Model.Name
	            </h1>
	        </div>
	        <div class="col-sm-6">
	            <div class="buttons-widget pull-right">
	                <a class="btn btn-md btn-danger" href="#" onclick="resetForm();">
	                    <i class="fa fa-times"></i> Cancel
	                </a>
	                <a href="#" onclick="submitForm();" class="btn btn-md btn-primary">
	                    <i class="fa fa-save"></i> @string.Format("{0}", Model.Id == 0 ? "Create" : "Save")
	                </a>
	            </div>
	        </div>
	    </div>
	    <!-- end: PAGE TITLE & BREADCRUMB -->
	</div>
</div>
<!-- end: PAGE HEADER -->
<!-- start: PAGE CONTENT -->
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" method="POST">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-external-link-square"></i>
                    @ViewBag.Title
                    <div class="panel-tools">
                        <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="row">
                                <div class="col-sm-12">
                                    <h5>Item Info</h5>
                                    <p/>
                                    <hr/>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" for="Name">
                                            Item Name
                                        </label>
                                        <div class="col-sm-8">
                                            @Html.TextBox("Name", Model.Name, new {@class = "form-control", placeholder = "Item Name", id = "Name"})
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" for="FoodTypeId">
                                            Item Type
                                        </label>
                                        <div class="col-sm-8">
                                            @Html.DropDownList("FoodTypeId", (List<SelectListItem>) ViewBag.FoodTypes, new {id = "FoodTypeId", @class = "form-control"})
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" for="DisplayName">
                                            Display Name
                                        </label>
                                        <div class="col-sm-8">
                                            @Html.TextBox("DisplayName", Model.DisplayName, new {@class = "form-control", placeholder = "Display Name", id = "DisplayName"})
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" for="PortionSize">
                                            Portion Size
                                            <span class="symbol required"></span>
                                        </label>
                                        <div class="col-sm-8">
                                            @Html.TextBox("PortionSize", Model.PortionSize, new {@class = "form-control", placeholder = "Portion Size", id = "PortionSize"})
                                        </div>
                                    </div>
                                    @if (Model.Id > 0)
                                    {
                                        <div class="form-group">
                                            <label class="col-sm-4 control-label" for="ModifiedReason">
                                                Modified Reason
                                            </label>
                                            <div class="col-sm-8">
                                                <textarea class="form-control limited" id="ModifiedReason" maxlength="150" name="ModifiedReason">@Model.ModifiedReason</textarea>
                                            </div>
                                        </div>
                                    }
                                </div>

                            </div>


                        </div>
                        <div class="col-sm-8">
                            <div class="row">
                                <div class="col-sm-12">
                                    <h5>Ingredients</h5>
                                    <p/>
                                    <hr/>
                                </div>


                                @for (var i = 0; i < Model.FoodIngredients.Count; i++)
                                {
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label class="col-sm-6 control-label" for="@string.Format("FoodIngredients_{0}__Value", i)">
                                                @Model.FoodIngredients[i].IngredientType.Text
                                            </label>
                                            <div class="col-sm-4">

                                                @Html.TextBox(string.Format("FoodIngredients[{0}].Value", i), Model.FoodIngredients[i].Value, new {id = string.Format("FoodIngredients_{0}__Value", i), @class = "form-control currency", placeholder = "Value"})
                                                @Html.Hidden(string.Format("FoodIngredients[{0}].IngredientType", i), Model.FoodIngredients[i].IngredientType.Id, new {id = string.Format("FoodIngredients_{0}__IngredientType", i)})
                                                @Html.Hidden(string.Format("FoodIngredients[{0}].Id", i), Model.FoodIngredients[i].Id, new {id = string.Format("FoodIngredients_{0}__Id", i)})
                                            </div>
                                        </div>
                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                    @Html.HiddenFor(k => k.Id)
                </div>
            </div>

        </form>
    </div>
</div>
<script>
    function submitForm() {
        $('form')[0].submit();
    }
    function resetForm() {
        $('form')[0].reset();
    }
</script>

better4you/Better4You/UI/Better4You.UI.Mvc/Views/Food/Index.cshtml
@model IEnumerable<FoodListItemView>
@{
    ViewBag.Title = "Item Management";
}
<!-- start: PAGE HEADER -->
<div class="row">
	<div class="col-sm-12">
		<!-- start: PAGE TITLE & BREADCRUMB -->
		<ol class="breadcrumb">
			<li>
			    <i class="clip-home-3"></i>
			    <a href="#">
			        Home
			    </a>
			</li>
			<li class="active">
			    Item Management
			</li>
		</ol>
	    <div class="row page-header">
	        <div class="col-sm-6">
	            <h1>
	                @ViewBag.Title
	            </h1>
	        </div>
	        <div class="col-sm-6">
	            <div class="buttons-widget pull-right">
	                <a class="btn btn-md btn-danger" href="@Url.Action("Edit", "Food")">
	                    <i class="fa fa-plus"></i>  Create
	                </a>
	            </div>
	        </div>
	    </div>
	    <!-- end: PAGE TITLE & BREADCRUMB -->
	</div>
</div>
<!-- end: PAGE HEADER -->
<!-- start: PAGE CONTENT -->
<div class="row">
    <div class="col-md-12">
        <form class="form" method="POST">
            <!-- start: RESPONSIVE TABLE PANEL -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-external-link-square"></i>
                    Search Criteria
                    <div class="panel-tools">
                        <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="table-responsive">
                                <table class="table table-condensed">
                                    <tr>
                                        <td class="col-sm-3">Item Name</td>
                                        <td>
                                            <input type="text" class="form-control limited" maxlength="50" placeholder="Item Name" title="Item Name" id="Name" name="Name"/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Item Type
                                        </td>
                                        <td>
                                            @Html.DropDownList("FoodTypeId", ((List<Tar.ViewModel.GeneralItemView>) ViewBag.FoodTypes).Select(d => new SelectListItem {Selected = d.Id == 0 ? true : false, Text = d.Text, Value = d.Id.ToString()}).ToList(), new {id = "FoodTypeId", @class = "form-control"})
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="table-responsive">
                                <table class="table table-condensed">
                                    <tr>
                                        <td class="col-sm-3">Display Name</td>
                                        <td>
                                            <input type="text" class="form-control limited" maxlength="50" placeholder="Display Name" title="Display Name" id="DisplayName" name="DisplayName"/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="col-sm-3">Portion Size</td>
                                        <td>
                                            <input type="text" class="form-control limited" maxlength="10" placeholder="Portion Size" title="Portion Size" id="PortionSize" name="PortionSize"/>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="table-responsive">
                                <table class="table table-condensed">
                                    <tr>
                                        <td><span class="form-control limited" style="visibility: hidden">&nbsp;</span></td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="pull-right">
                                                    <button type="submit" class="btn btn-md btn-blue"><i class="clip-search"></i>  Search</button>
                                                </span>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!-- start: RESPONSIVE TABLE PANEL -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-external-link-square"></i>
                Search Result
                <div class="panel-tools">
                    <a class="btn btn-xs btn-link panel-collapse collapses" href="#">
                    </a>
                </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-condensed">
                        <thead>
                        <tr>
                            <th class="center">...</th>
                            <th class="center">Type</th>
                            <th class="center">Name</th>
                            <th class="center">Display</th>
                            <th class="center">Portion Size</th>
                            <th class="center">Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="center">
                                    <div class="visible-md visible-lg hidden-sm hidden-xs">
                                        <a href="@Url.Action("Edit", "Food", new {Id = item.Id})" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
                                    </div>
                                </td>
                                <td>
                                     @item.FoodType.Text                                    
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Food", new {Id = item.Id})">@item.Name</a>  
                                </td>
                                <td>
                                    <span class="pull-left">@item.DisplayName</span>
                                </td>
                                <td>
                                    <span class="pull-risht">@item.PortionSize</span>
                                </td> 
                                <td class="center">
                                  @item.RecordStatus.Text
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end: PAGE CONTENT-->

better4you/Better4You/UI/Better4You.UI.Mvc/Views/Food/Percentage.cshtml
@model IList<FoodPercentageView>
@{
    ViewBag.Title = "Fruit Vegetable Percentages";
}

<!-- start: PAGE HEADER -->
<div class="row">
    <div class="col-sm-12">
        <!-- start: PAGE TITLE & BREADCRUMB -->
        <ol class="breadcrumb">
            <li>
                <i class="clip-home-3"></i>
                <a href="#">
                    Home
                </a>
            </li>
            <li class="active">
                @ViewBag.Title
            </li>
        </ol>
        <div class="row page-header">
            <div class="col-sm-6">
                <h1>
                    @ViewBag.Title
                </h1>
            </div>
            <div class="col-sm-6">
                <div class="buttons-widget pull-right">
                    <a href="#" onclick="$('form')[0].submit();" class="btn btn-md btn-primary">
                        <i class="fa fa-save"></i> Save
                    </a>
                </div>
            </div>
        </div>
        <!-- end: PAGE TITLE & BREADCRUMB -->
    </div>
</div>
<!-- end: PAGE HEADER -->
<!-- start: PAGE CONTENT -->
<div class="row">
    <div class="col-md-8">
        <form class="form-horizontal" method="POST">
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-condensed">
                    <thead>
                        <tr>
                            <th class="center col-sm-5">Meal</th>
                            <th class="center col-sm-2">Fruit (%)</th>
                            <th class="center col-sm-2">Vegetable (%)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (var i = 0; i < Model.Count(); i++)
                        {
                            <tr>
                                <td>
                                    @Model[i].MealType.Text
                                </td>
                                <td>
                                    @Html.TextBox(string.Format("FoodPercentages[{0}].Fruit", i), Model[i].Fruit, new { id = string.Format("FoodPercentages_{0}__Fruit", i), @class = "form-control", type = "number", min = "0", max = "200", placeholder = "Value" })
                                </td>
                                <td>
                                    @Html.TextBox(string.Format("FoodPercentages[{0}].Vegetable", i), Model[i].Vegetable, new { id = string.Format("FoodPercentages_{0}__Vegetable", i), @class = "form-control", type = "number", min = "0", max = "200", placeholder = "Value" })
                                </td>
                            </tr>
                            @Html.Hidden(string.Format("FoodPercentages[{0}].MealType", i), Model[i].MealType.Id, new { id = string.Format("FoodPercentages_{0}__MealType", i) })
                            @Html.Hidden(string.Format("FoodPercentages[{0}].Id", i), Model[i].Id, new { id = string.Format("FoodPercentages_{0}__Id", i) })

                        }
                        <input type="hidden" name="foodPercentageCount" id="foodPercentageCount" value="@Model.Count()" />
                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>